[package]
name = "core"
version = "0.1.0"
authors = ["Frederic Desgreniers <fredericdesgreniers@gmail.com>"]
build = "build.rs"

[dependencies]
rayon = "1.0.0"


[dependencies.sdl2]
version = "0.31.0"
default-features = false
features = ["ttf"]